name       : pam-u2f
version    : 1.0.8
release    : 7
source     :
    - https://github.com/Yubico/pam-u2f/archive/pam_u2f-1.0.8.tar.gz : f470385a342ccc4fe55e2f43d6cdfef46ced243b51a3e6411b02a68603f28337
license    : BSD-2-Clause
component  : security
summary    : Pluggable Authentication Module (PAM) for U2F
description: |
    This module implements PAM over U2F, providing an easy way to integrate the YubiKey (or other U2F compliant authenticators) into your existing infrastructure.
builddeps  :
    - pkgconfig(u2f-host)
    - pkgconfig(u2f-server)
    - asciidoc
setup      : |
    %reconfigure --with-pam-dir=%libdir%/security/
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
