name       : pam-u2f
version    : 1.0.7
release    : 4
source     :
    - https://github.com/Yubico/pam-u2f/archive/pam_u2f-1.0.7.tar.gz : 02d33ba0daeb7552d633658cbf04841dc8224b3bba9ea4e3a25880a66d4cc625
license    : BSD-2-Clause
component  : security
summary    : Pluggable Authentication Module (PAM) for U2F
description: |
    This module implements PAM over U2F, providing an easy way to integrate the YubiKey (or other U2F compliant authenticators) into your existing infrastructure.
builddeps  :
    - pkgconfig(u2f-host)
    - pkgconfig(u2f-server)
    - asciidoc
setup      : |
    %autogen --with-pam-dir=/lib/security/
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
